version: "3.9"

services:
  db:
    image: postgres:16.2
    container_name: postgres
    restart: always
#    user: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=trash
    ports:
     - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgresql/data
     - /:/app
    networks:
      inteamnet:
        ipv4_address: 10.1.0.100

  python:
    build: ./python
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./python:/app
      - ./public:/public
    command: ["uvicorn", "main:app", "--reload", "--workers", "1", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      inteamnet:
        ipv4_address: 10.1.0.101

#  frontend:
#    build: ./frontend
#    container_name: frontend
#    ports:
#      - 80:5173
#    environment:
#        NODE_ENV: production
#    volumes:
#      - ./frontend:/frontend
#      - ./public:/public
#    stdin_open: true
#    tty: true
#    networks:
#      inteamnet:
#        ipv4_address: 10.1.0.104

networks:
  inteamnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

volumes:
  pgadmin:
  pgdata:
