version: "3.9"

services:
  db:
    image: postgres:16.2
    container_name: postgres
    restart: always
#    user: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=trash
    ports:
     - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgresql/data
    networks:
      inteamnet:
        ipv4_address: 10.1.0.100

  python:
    build: ./python
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./python:/app
      - ./public:/public
    command: ["uvicorn", "main:app", "--reload", "--workers", "1", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      inteamnet:
        ipv4_address: 10.1.0.101

#  frontend:
#    build: ./frontend
#    container_name: frontend
#    ports:
#      - 80:5173
#    environment:
#        NODE_ENV: production
#    volumes:
#      - ./frontend:/frontend
#      - ./public:/public
#    stdin_open: true
#    tty: true
#    networks:
#      inteamnet:
#        ipv4_address: 10.1.0.104

  pgadmin:
    image: dpage/pgadmin4:8.5
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
#      - ./backup.sql:/var/lib/pgadmin/storage/admin_pgadmin.com/backup.sql
    depends_on:
      - db
    networks:
      inteamnet:
       ipv4_address: 10.1.0.102

#  go:
#    build: ./go
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./go:/usr/local/go/src/
  apache:
    build: ./apache
    container_name: apache_php
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./apache/www:/htdocs
      - ./public:/public
    networks:
      inteamnet:
        ipv4_address: 10.1.0.103


networks:
  inteamnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

volumes:
  pgadmin:
  pgdata:
